// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCgOrkJQvoVt2JwMmhelPrKrb3DRW_ac',
    appId: '1:409590286140:web:879d7a44465e6769398039',
    messagingSenderId: '409590286140',
    projectId: 'push-notification-2bd17',
    authDomain: 'push-notification-2bd17.firebaseapp.com',
    storageBucket: 'push-notification-2bd17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOfxWfB9Mh4PqHxDggwN3rmZyrVwZgdE',
    appId: '1:409590286140:android:65f8b789a11c2d80398039',
    messagingSenderId: '409590286140',
    projectId: 'push-notification-2bd17',
    storageBucket: 'push-notification-2bd17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2b1pojcuwH1gomgMz6IlNBBlECF4go8Q',
    appId: '1:409590286140:ios:3c2d5459bcaefcd4398039',
    messagingSenderId: '409590286140',
    projectId: 'push-notification-2bd17',
    storageBucket: 'push-notification-2bd17.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2b1pojcuwH1gomgMz6IlNBBlECF4go8Q',
    appId: '1:409590286140:ios:3c2d5459bcaefcd4398039',
    messagingSenderId: '409590286140',
    projectId: 'push-notification-2bd17',
    storageBucket: 'push-notification-2bd17.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpCgOrkJQvoVt2JwMmhelPrKrb3DRW_ac',
    appId: '1:409590286140:web:04c1795907bc45ef398039',
    messagingSenderId: '409590286140',
    projectId: 'push-notification-2bd17',
    authDomain: 'push-notification-2bd17.firebaseapp.com',
    storageBucket: 'push-notification-2bd17.firebasestorage.app',
  );
}
